services:
  pyspark:
    image: "jupyter/pyspark-notebook"
    volumes:
      - data:/var/lib/jupyter-pyspark/data:rw
    ports:
      - 8888:8888
      - 4040:4040
    networks:
      - network2
networks:
  network2:
    name: pyspark-network
    external: true
volumes:
  data: